name: Run tests
on: [push]
jobs:
    build:
        name: Test
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - uses: actions/setup-node@master
              with:
                  node-version: 10.x
            - run: npm install
            - run: npm run dist
            - run: npm run citest
